name: Validate Content

on:
  pull_request:
    branches: [ main, develop, release/* ]
    paths:
      - 'resume/**'
      - 'linkedin/**'
      - 'job_search/**'
      - 'tests/**'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install markdownlint
        run: npm install -g markdownlint-cli
        
      - name: Run markdownlint
        run: markdownlint '**/*.md' --ignore node_modules
        
  check-resume-structure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Validate Resume Structure
        run: |
          python -c "
import os
import sys

# Define required files
required_resume_sections = [
    'resume/sections/summary_enhanced.md',
    'resume/sections/skills_structured.md',
    'resume/sections/experience_structured.md',
    'resume/sections/education_enhanced.md'
]

# Check for missing files
missing_files = [f for f in required_resume_sections if not os.path.exists(f)]

if missing_files:
    print(f'Error: The following required resume sections are missing: {missing_files}')
    sys.exit(1)
else:
    print('✅ All required resume sections present')

# Validate that experience entries have metrics
exp_file = 'resume/sections/experience_structured.md'
with open(exp_file, 'r') as f:
    content = f.read()
    
if not any(x in content for x in ['%', 'increased', 'decreased', 'reduced', 'improved']):
    print('Error: Experience section lacks quantifiable metrics')
    sys.exit(1)
else:
    print('✅ Experience section contains metrics')

# Validate full resume exists
if not os.path.exists('resume/versions/full_resume.md'):
    print('Error: Full resume markdown version missing')
    sys.exit(1)
else:
    print('✅ Full resume present')

print('All validation checks passed!')
          "
          
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install cspell
        run: npm install -g cspell
        
      - name: Run spell check
        run: |
          cspell "**/*.md" --no-progress